package com.goods.entity;

public class Cutomer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cutomer.cutomerid
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	private Integer cutomerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cutomer.cutomermc
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	private String cutomermc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cutomer.userid
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cutomer.kehudanwei
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	private String kehudanwei;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cutomer.cutomerid
	 * @return  the value of cutomer.cutomerid
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	public Integer getCutomerid() {
		return cutomerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cutomer.cutomerid
	 * @param cutomerid  the value for cutomer.cutomerid
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	public void setCutomerid(Integer cutomerid) {
		this.cutomerid = cutomerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cutomer.cutomermc
	 * @return  the value of cutomer.cutomermc
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	public String getCutomermc() {
		return cutomermc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cutomer.cutomermc
	 * @param cutomermc  the value for cutomer.cutomermc
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	public void setCutomermc(String cutomermc) {
		this.cutomermc = cutomermc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cutomer.userid
	 * @return  the value of cutomer.userid
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cutomer.userid
	 * @param userid  the value for cutomer.userid
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cutomer.kehudanwei
	 * @return  the value of cutomer.kehudanwei
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	public String getKehudanwei() {
		return kehudanwei;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cutomer.kehudanwei
	 * @param kehudanwei  the value for cutomer.kehudanwei
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	public void setKehudanwei(String kehudanwei) {
		this.kehudanwei = kehudanwei;
	}
}