package com.goods.entity;

public class Goods {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.goodsid
	 * @mbggenerated  Fri Dec 01 14:46:32 CST 2017
	 */
	private Integer goodsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.userid
	 * @mbggenerated  Fri Dec 01 14:46:32 CST 2017
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.type
	 * @mbggenerated  Fri Dec 01 14:46:32 CST 2017
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.xinghao
	 * @mbggenerated  Fri Dec 01 14:46:32 CST 2017
	 */
	private String xinghao;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.danjia
	 * @mbggenerated  Fri Dec 01 14:46:32 CST 2017
	 */
	private String danjia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods.goodsname
	 * @mbggenerated  Fri Dec 01 14:46:32 CST 2017
	 */
	private String goodsname;
	
	private String danwei;
	
	public String getDanwei() {
		return danwei;
	}

	public void setDanwei(String danwei) {
		this.danwei = danwei;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.goodsid
	 * @return  the value of goods.goodsid
	 * @mbggenerated  Fri Dec 01 14:46:32 CST 2017
	 */
	public Integer getGoodsid() {
		return goodsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.goodsid
	 * @param goodsid  the value for goods.goodsid
	 * @mbggenerated  Fri Dec 01 14:46:32 CST 2017
	 */
	public void setGoodsid(Integer goodsid) {
		this.goodsid = goodsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.userid
	 * @return  the value of goods.userid
	 * @mbggenerated  Fri Dec 01 14:46:32 CST 2017
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.userid
	 * @param userid  the value for goods.userid
	 * @mbggenerated  Fri Dec 01 14:46:32 CST 2017
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.type
	 * @return  the value of goods.type
	 * @mbggenerated  Fri Dec 01 14:46:32 CST 2017
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.type
	 * @param type  the value for goods.type
	 * @mbggenerated  Fri Dec 01 14:46:32 CST 2017
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.xinghao
	 * @return  the value of goods.xinghao
	 * @mbggenerated  Fri Dec 01 14:46:32 CST 2017
	 */
	public String getXinghao() {
		return xinghao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.xinghao
	 * @param xinghao  the value for goods.xinghao
	 * @mbggenerated  Fri Dec 01 14:46:32 CST 2017
	 */
	public void setXinghao(String xinghao) {
		this.xinghao = xinghao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.danjia
	 * @return  the value of goods.danjia
	 * @mbggenerated  Fri Dec 01 14:46:32 CST 2017
	 */
	public String getDanjia() {
		return danjia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.danjia
	 * @param danjia  the value for goods.danjia
	 * @mbggenerated  Fri Dec 01 14:46:32 CST 2017
	 */
	public void setDanjia(String danjia) {
		this.danjia = danjia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods.goodsname
	 * @return  the value of goods.goodsname
	 * @mbggenerated  Fri Dec 01 14:46:32 CST 2017
	 */
	public String getGoodsname() {
		return goodsname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods.goodsname
	 * @param goodsname  the value for goods.goodsname
	 * @mbggenerated  Fri Dec 01 14:46:32 CST 2017
	 */
	public void setGoodsname(String goodsname) {
		this.goodsname = goodsname;
	}
}