package com.goods.entity;


public class Order {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.orderid
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	private String orderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.cutomerid
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	private Integer cutomerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.userid
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.zt
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	private String zt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.jine
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	private String jine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.fukuane
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	private String fukuane;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.timedate
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	private String timedate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.orderid
	 * @return  the value of order.orderid
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public String getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.orderid
	 * @param orderid  the value for order.orderid
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.cutomerid
	 * @return  the value of order.cutomerid
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public Integer getCutomerid() {
		return cutomerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.cutomerid
	 * @param cutomerid  the value for order.cutomerid
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public void setCutomerid(Integer cutomerid) {
		this.cutomerid = cutomerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.userid
	 * @return  the value of order.userid
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.userid
	 * @param userid  the value for order.userid
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.zt
	 * @return  the value of order.zt
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public String getZt() {
		return zt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.zt
	 * @param zt  the value for order.zt
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public void setZt(String zt) {
		this.zt = zt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.jine
	 * @return  the value of order.jine
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public String getJine() {
		return jine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.jine
	 * @param jine  the value for order.jine
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public void setJine(String jine) {
		this.jine = jine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.fukuane
	 * @return  the value of order.fukuane
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public String getFukuane() {
		return fukuane;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.fukuane
	 * @param fukuane  the value for order.fukuane
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public void setFukuane(String fukuane) {
		this.fukuane = fukuane;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.timedate
	 * @return  the value of order.timedate
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public String getTimedate() {
		return timedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.timedate
	 * @param timedate  the value for order.timedate
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public void setTimedate(String timedate) {
		this.timedate = timedate;
	}
}