package com.goods.entity;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderid
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goodsid
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.cutomerid
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    private Integer cutomerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.userid
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.num
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.zt
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    private String zt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.jine
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    private String jine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.fukuane
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    private String fukuane;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.time
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderid
     *
     * @return the value of order.orderid
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderid
     *
     * @param orderid the value for order.orderid
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goodsid
     *
     * @return the value of order.goodsid
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goodsid
     *
     * @param goodsid the value for order.goodsid
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.cutomerid
     *
     * @return the value of order.cutomerid
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    public Integer getCutomerid() {
        return cutomerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.cutomerid
     *
     * @param cutomerid the value for order.cutomerid
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    public void setCutomerid(Integer cutomerid) {
        this.cutomerid = cutomerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.userid
     *
     * @return the value of order.userid
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.userid
     *
     * @param userid the value for order.userid
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.num
     *
     * @return the value of order.num
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.num
     *
     * @param num the value for order.num
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.zt
     *
     * @return the value of order.zt
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    public String getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.zt
     *
     * @param zt the value for order.zt
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    public void setZt(String zt) {
        this.zt = zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.jine
     *
     * @return the value of order.jine
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    public String getJine() {
        return jine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.jine
     *
     * @param jine the value for order.jine
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    public void setJine(String jine) {
        this.jine = jine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.fukuane
     *
     * @return the value of order.fukuane
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    public String getFukuane() {
        return fukuane;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.fukuane
     *
     * @param fukuane the value for order.fukuane
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    public void setFukuane(String fukuane) {
        this.fukuane = fukuane;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.time
     *
     * @return the value of order.time
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.time
     *
     * @param time the value for order.time
     *
     * @mbggenerated Tue Nov 28 14:15:10 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }
}