package com.goods.entity;

public class Orderetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderetail.id
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderetail.orderid
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	private String orderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderetail.goodsid
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	private String goodsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderetail.goodsname
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	private String goodsname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderetail.num
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	private Integer num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderetail.price
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	private Float price;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderetail.id
	 * @return  the value of orderetail.id
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderetail.id
	 * @param id  the value for orderetail.id
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderetail.orderid
	 * @return  the value of orderetail.orderid
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public String getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderetail.orderid
	 * @param orderid  the value for orderetail.orderid
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderetail.goodsid
	 * @return  the value of orderetail.goodsid
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public String getGoodsid() {
		return goodsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderetail.goodsid
	 * @param goodsid  the value for orderetail.goodsid
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public void setGoodsid(String goodsid) {
		this.goodsid = goodsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderetail.goodsname
	 * @return  the value of orderetail.goodsname
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public String getGoodsname() {
		return goodsname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderetail.goodsname
	 * @param goodsname  the value for orderetail.goodsname
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public void setGoodsname(String goodsname) {
		this.goodsname = goodsname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderetail.num
	 * @return  the value of orderetail.num
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderetail.num
	 * @param num  the value for orderetail.num
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderetail.price
	 * @return  the value of orderetail.price
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public Float getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderetail.price
	 * @param price  the value for orderetail.price
	 * @mbggenerated  Thu Dec 07 09:23:52 CST 2017
	 */
	public void setPrice(Float price) {
		this.price = price;
	}
}