package com.goods.entity;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.userid
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.userpass
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	private String userpass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.danwei
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	private String danwei;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.userid
	 * @return  the value of user.userid
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.userid
	 * @param userid  the value for user.userid
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.userpass
	 * @return  the value of user.userpass
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	public String getUserpass() {
		return userpass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.userpass
	 * @param userpass  the value for user.userpass
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	public void setUserpass(String userpass) {
		this.userpass = userpass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.danwei
	 * @return  the value of user.danwei
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	public String getDanwei() {
		return danwei;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.danwei
	 * @param danwei  the value for user.danwei
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	public void setDanwei(String danwei) {
		this.danwei = danwei;
	}
}