package com.goods.dao;

import com.goods.entity.Cutomer;

public interface CutomerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cutomer
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	int deleteByPrimaryKey(Integer cutomerid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cutomer
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	int insert(Cutomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cutomer
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	int insertSelective(Cutomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cutomer
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	Cutomer selectByPrimaryKey(Integer cutomerid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cutomer
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	int updateByPrimaryKeySelective(Cutomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cutomer
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	int updateByPrimaryKey(Cutomer record);
}