package com.goods.dao;

import com.goods.entity.Goods;

public interface GoodsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	int deleteByPrimaryKey(Integer goodsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	int insert(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	int insertSelective(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	Goods selectByPrimaryKey(Integer goodsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	int updateByPrimaryKeySelective(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Tue Nov 28 14:15:10 CST 2017
	 */
	int updateByPrimaryKey(Goods record);
}