package com.goods.dao;

import java.util.List;

import com.goods.entity.OrderInfo;
import com.goods.entity.Orderetail;

public interface OrderetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderetail
	 * @mbggenerated  Thu Dec 07 09:15:48 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderetail
	 * @mbggenerated  Thu Dec 07 09:15:48 CST 2017
	 */
	int insert(Orderetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderetail
	 * @mbggenerated  Thu Dec 07 09:15:48 CST 2017
	 */
	int insertSelective(Orderetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderetail
	 * @mbggenerated  Thu Dec 07 09:15:48 CST 2017
	 */
	Orderetail selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderetail
	 * @mbggenerated  Thu Dec 07 09:15:48 CST 2017
	 */
	int updateByPrimaryKeySelective(Orderetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderetail
	 * @mbggenerated  Thu Dec 07 09:15:48 CST 2017
	 */
	int updateByPrimaryKey(Orderetail record);
	
	public int saveOrderetail(Orderetail orderetail);
	
	public List<OrderInfo> getOrderetail(String orderid);
}